name: Docker Setup
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
    # ---------------- DOCKER BUILD ----------------
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cart-service:${{ inputs.image_tag }} .

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/cart-service:${{ inputs.image_tag }} 
        Format: 'table'
        severity: HIGH,CRITICAL
        exit-code: '0'
    # ---------------- DOCKER HUB LOGIN ----------------
    # - name: Login to Docker Hub
    #   run: |
    #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # # ---------------- PUSH IMAGE ----------------
    # - name: Push Image
    #   run: |
    #     docker push ${{ secrets.DOCKER_USERNAME }}/cart-service:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/cart-service:${{ github.sha }}
